"""add oauth models

Revision ID: 39ff37cde915
Revises: 9ac769528126
Create Date: 2025-01-28 15:02:59.365891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ff37cde915'
down_revision: Union[str, None] = '9ac769528126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'oauth_states', ['state'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_states', type_='unique')
    # ### end Alembic commands ###
